Repository OpenVoiceOS/skill-ovos-randomness, pull requests merged in 2024-11, with the labels that each got.

#13 chore(automations): tidy up and get a release out
  .github/workflows/sync_tx.yml
  .github/workflows/test_resources.yml
Labels: ignore-for-release

#14 fix: standard naming for PyPi
  setup.py
  test/test_skill.py
Labels: fix

#15 feat: support more Python versions, fix workflows
  .github/workflows/build_tests.yml
  .github/workflows/publish_stable.yml
  .github/workflows/release_workflow.yml
  .github/workflows/skill_tests.yml
  README.md
  skill.json
Labels: feature

#17 fix: drop lingua-franca
  requirements.txt
  skill.json
  skill_randomness/__init__.py
Labels: fix
